-- Compare the RTL array with deterministic vectors generated by libcgra's emulator.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;
use std.env.all;
use work.cgra_pkg.all;

entity tb_array_diff is
end entity;

architecture sim of tb_array_diff is
  signal clk : std_logic := '0';
  signal rst : std_logic := '0';
  signal step : std_logic := '0';
  signal cfg : cfg_vec_t(0 to NUM_PE - 1) := (others => (others => '0'));
  signal west : data_vec_t(0 to ROWS - 1) := (others => (others => '0'));
  signal north : data_vec_t(0 to COLS - 1) := (others => (others => '0'));
  signal result : data_vec_t(0 to NUM_PE - 1);
begin
  dut : entity work.cgra_array
    port map (clk => clk, rst => rst, step => step,
              cfg => cfg, west_in => west, north_in => north, pe_out => result);

  stim : process
    file vectors : text open read_mode is "build/array_diff.vec";
    variable row : line;
    variable word_value : integer;
    variable steps : natural;
    variable expected : integer_vector(0 to NUM_PE - 1);
    variable case_no : natural := 0;
  begin
    while not endfile(vectors) loop
      readline(vectors, row);
      read(row, steps);
      for i in 0 to NUM_PE - 1 loop
        read(row, word_value);
        cfg(i) <= std_logic_vector(to_unsigned(word_value, CFG_W));
      end loop;
      for i in 0 to ROWS - 1 loop
        read(row, word_value);
        west(i) <= to_signed(word_value, DATA_W);
      end loop;
      for i in 0 to COLS - 1 loop
        read(row, word_value);
        north(i) <= to_signed(word_value, DATA_W);
      end loop;
      for i in 0 to NUM_PE - 1 loop
        read(row, expected(i));
      end loop;

      rst <= '1'; step <= '0';
      wait for 5 ns; clk <= '1'; wait for 5 ns; clk <= '0';
      rst <= '0'; step <= '1';
      for s in 1 to steps loop
        wait for 5 ns; clk <= '1'; wait for 5 ns; clk <= '0';
      end loop;
      wait for 1 ns;
      for i in 0 to NUM_PE - 1 loop
        assert to_integer(result(i)) = expected(i)
          report "array/emulator mismatch case=" & integer'image(case_no) &
                 " pe=" & integer'image(i) & " expected=" & integer'image(expected(i)) &
                 " got=" & integer'image(to_integer(result(i))) severity failure;
      end loop;
      wait for 4 ns; step <= '0';
      case_no := case_no + 1;
    end loop;
    assert case_no = 64 report "wrong vector count" severity failure;
    report "tb_array_diff PASSED (64 cases, 1024 PE results)";
    finish;
  end process;
end architecture;
